#!/usr/bin/env bash
# Generated by setup_cosmos_policy_uv.sh - source this before running any
# cosmos_policy Python command:
#   source "$(dirname "${BASH_SOURCE[0]}")/activate_cuda_env.sh"
_cosmos_env_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Pin HF_HOME to a fixed, repo-local cache dir (overriding any HF_HOME/module
# default from the surrounding shell) so downloads always land where the
# setup script's pre-fetch step put them - see setup_cosmos_policy_uv.sh.
export HF_HOME="$_cosmos_env_dir/.hf_cache"
_cosmos_site_packages="$(find "$_cosmos_env_dir/.venv/lib" -maxdepth 1 -type d -name 'python3.*' | head -n1)/site-packages"
_cosmos_cuda_home="$(find "$_cosmos_site_packages/nvidia" -maxdepth 1 -type d -name 'cu[0-9]*' 2>/dev/null | head -n1)"
if [[ -n "$_cosmos_cuda_home" ]]; then
  export CUDA_HOME="$_cosmos_cuda_home"
fi
_cosmos_ld_dirs="$(find "$_cosmos_site_packages/nvidia" -maxdepth 2 -type d -name lib 2>/dev/null | paste -sd: -)"
if [[ -n "$_cosmos_ld_dirs" ]]; then
  export LD_LIBRARY_PATH="$_cosmos_ld_dirs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
unset _cosmos_env_dir _cosmos_site_packages _cosmos_cuda_home _cosmos_ld_dirs
