#!/usr/bin/env bash
set -euo pipefail

# Native (non-Docker) setup for NVIDIA's Cosmos Policy using uv.
# https://github.com/nvlabs/cosmos-policy
#
# Usage:
#   bash setup_cosmos_policy_uv.sh [INSTALL_DIR]
#
# Example:
#   bash setup_cosmos_policy_uv.sh "$PWD/cosmos_policy"
#
# Requirements:
#   - git
#   - uv (https://docs.astral.sh/uv/getting-started/installation/)
#   - an NVIDIA GPU with CUDA 13.0 drivers (this script installs the "cu130" extra)
#   - system packages that the project's own docker/Dockerfile installs via apt,
#     since this script does not use Docker and will not sudo-install anything:
#       build-essential cmake ffmpeg git-lfs libgl1 libegl1-mesa-dev \
#       libgl1-mesa-dri libglib2.0-0
#     Plus libglu1-mesa (not in the Dockerfile, but needed by robosuite's EGL
#     context teardown - without it you'll see a harmless-but-noisy
#     "libGLU.so.0: cannot open shared object file" during interpreter
#     shutdown, after a LIBERO eval already finished successfully):
#     On Debian/Ubuntu:
#       sudo apt-get install -y build-essential cmake ffmpeg git-lfs libgl1 \
#         libegl1-mesa-dev libgl1-mesa-dri libglib2.0-0 libglu1-mesa
#
# This script installs the "libero" task group (LIBERO simulation benchmark).
# robocasa and aloha are mutually exclusive alternatives - see LIBERO.md /
# ROBOCASA.md / ALOHA.md in the cloned repo if you need a different one.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${1:-$SCRIPT_DIR/cosmos_policy}"
CUDA_EXTRA="cu130"
TASK_GROUP="libero"
PYTHON_VERSION="3.10"

# Resolve relative install paths from the caller's cwd (not from inside REPO_DIR).
if [[ "$INSTALL_DIR" != /* ]]; then
  INSTALL_DIR="$(pwd)/$INSTALL_DIR"
fi
REPO_DIR="$INSTALL_DIR"

command -v git >/dev/null 2>&1 || {
  echo "Error: git is required." >&2
  exit 1
}

command -v uv >/dev/null 2>&1 || {
  echo "Error: uv is required." >&2
  echo "Install it from https://docs.astral.sh/uv/getting-started/installation/" >&2
  exit 1
}

for tool in cmake ffmpeg gcc; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "Warning: '$tool' was not found on PATH." >&2
    echo "  Cosmos Policy's own Dockerfile installs it via apt; some pip/uv" >&2
    echo "  builds (e.g. mujoco, flash-attn) may fail to compile without it." >&2
  }
done

# cosmos_policy is meant to live as plain, committable source under this
# repo (not a nested git checkout - a nested .git makes the parent repo treat
# it as an opaque gitlink instead of tracking its files). If the source is
# already present (e.g. already committed here), leave it alone. Otherwise
# fetch it via a throwaway git clone and immediately strip its .git, so the
# result is just files, ready to be committed to the parent repo.
if [[ -f "$REPO_DIR/pyproject.toml" ]]; then
  echo "cosmos-policy source already present at $REPO_DIR"
else
  if [[ -e "$REPO_DIR" ]]; then
    echo "Removing incomplete install directory at $REPO_DIR"
    rm -rf "$REPO_DIR"
  fi
  git clone https://github.com/nvlabs/cosmos-policy.git "$REPO_DIR"
  rm -rf "$REPO_DIR/.git"
fi

REPO_DIR="$(cd "$REPO_DIR" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
UV_HOME_DIR="$REPO_DIR/.uv_home"
export UV_HOME="$UV_HOME_DIR"
export XDG_DATA_HOME="$UV_HOME_DIR/xdg_data"
export XDG_CACHE_HOME="$UV_HOME_DIR/xdg_cache"
export UV_PYTHON_INSTALL_DIR="$REPO_DIR/.uv_python"

# Ensure uv cache/temp are writable even in restricted/sandboxed environments.
mkdir -p "$REPO_DIR/.uv_cache" "$REPO_DIR/.uv_tmp"
export UV_CACHE_DIR="$REPO_DIR/.uv_cache"
export TMPDIR="$REPO_DIR/.uv_tmp"

cd "$REPO_DIR"

# pyproject.toml requires Python >= 3.10; uv downloads a compatible
# interpreter automatically when necessary.
mkdir -p "$UV_PYTHON_INSTALL_DIR"
uv python install "$PYTHON_VERSION" --install-dir "$UV_PYTHON_INSTALL_DIR" --no-bin

# Resolve and install the pinned dependencies (core + cu130 CUDA extra +
# libero task group) into a uv-managed venv at $REPO_DIR/.venv.
uv sync --extra "$CUDA_EXTRA" --group "$TASK_GROUP" --python "$PYTHON_VERSION"

# On hosts with no system-wide CUDA toolkit (no nvcc, nothing in ldconfig),
# transformer_engine/megatron-core still try to locate CUDA .so files via
# CUDA_HOME and ldconfig, using a search layout that predates the current
# consolidated "nvidia-cuXX" pip wheels (which put every CUDA library under a
# single nvidia/cuXX/lib/ dir instead of one dir per library). Without this,
# `import transformer_engine` fails with e.g.
# "subprocess.CalledProcessError: ldconfig -p | grep 'libnvrtc.so'" or later
# "OSError: libcublas.so.13: cannot open shared object file". Generate an env
# file that points CUDA_HOME/LD_LIBRARY_PATH at the venv's own CUDA libs so
# any script that sources it can import these packages successfully.
ENV_FILE="$REPO_DIR/activate_cuda_env.sh"
cat >"$ENV_FILE" <<'ENVEOF'
#!/usr/bin/env bash
# Generated by setup_cosmos_policy_uv.sh - source this before running any
# cosmos_policy Python command:
#   source "$(dirname "${BASH_SOURCE[0]}")/activate_cuda_env.sh"
_cosmos_env_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Repin uv's own cache/home/python-install dirs to the same repo-local paths
# setup_cosmos_policy_uv.sh installed everything into (it only exported these
# for its own process, so a fresh shell - e.g. on a different compute node -
# never saw them). Without this, `uv run`/`uv sync` fall back to uv's default
# (non-repo-local) cache, find it empty, and try to re-resolve/download
# packages - which hangs or fails on compute nodes with no internet access,
# even though everything is already installed at these paths.
export UV_HOME="$_cosmos_env_dir/.uv_home"
export XDG_DATA_HOME="$UV_HOME/xdg_data"
export XDG_CACHE_HOME="$UV_HOME/xdg_cache"
export UV_PYTHON_INSTALL_DIR="$_cosmos_env_dir/.uv_python"
export UV_CACHE_DIR="$_cosmos_env_dir/.uv_cache"
export TMPDIR="$_cosmos_env_dir/.uv_tmp"
# Single per-cluster knob for every large on-disk artifact this project reads
# or writes (HF cache, LIBERO dataset, KD inits, training output). Everything
# below - and every conf/runs/*.yaml, via ${oc.env:COSMOS_POLICY_STORAGE,...} -
# derives from it, so moving to a new cluster is just changing this one line
# (or exporting COSMOS_POLICY_STORAGE / COSMOS_POLICY_ACCOUNT before sourcing).
# The value here is this checkout's current cluster; the yaml defaults still
# carry the original rrg-gberseth paths for reference.
export COSMOS_POLICY_STORAGE="${COSMOS_POLICY_STORAGE:-/project/aip-courvill/esraa1}"
export COSMOS_POLICY_ACCOUNT="${COSMOS_POLICY_ACCOUNT:-aip-courvill}"
# Slurm GRES GPU type for every job submit_sweep.py generates (--gres=gpu:<type>:<n>).
# rrg-gberseth was "h100"; Vulcan / aip-courvill is "l40s". submit_sweep.py's RunConfig.gpu_type
# reads this at submit time; override per run with runs.<name>.gpu_type=... on the CLI.
export COSMOS_POLICY_GPU_TYPE="${COSMOS_POLICY_GPU_TYPE:-l40s}"
# Pin HF_HOME to a fixed cache dir (overriding any HF_HOME/module default
# from the surrounding shell) so downloads always land where the setup
# script's pre-fetch step put them - see setup_cosmos_policy_uv.sh. This
# points at the project storage allocation, not a repo-local dir under
# $HOME: checkpoints/tokenizers here run into the tens of GB, easily large
# enough to blow a small $HOME quota on clusters (e.g. Compute Canada RRG
# allocations) - same reasoning as DATASETS_DIR below. Override with
# COSMOS_POLICY_HF_HOME (full path) or COSMOS_POLICY_STORAGE (root) if this
# path isn't right for you.
export HF_HOME="${COSMOS_POLICY_HF_HOME:-$COSMOS_POLICY_STORAGE/hf_cache}"
# Everything this setup script pre-fetches (pretrained checkpoint, tokenizer,
# base-model checkpoints eagerly resolved by cosmos_policy_experiment_configs.py
# at import time, LIBERO simulator assets) is already cached under HF_HOME
# above. Without HF_HUB_OFFLINE=1, huggingface_hub still attempts a live
# network check before falling back to that cache - which hangs/fails outright
# on compute nodes with no internet access (e.g. "Network is unreachable" from
# get_checkpoint_by_hf), even though nothing actually needs downloading.
export HF_HUB_OFFLINE=1
_cosmos_site_packages="$(find "$_cosmos_env_dir/.venv/lib" -maxdepth 1 -type d -name 'python3.*' | head -n1)/site-packages"
_cosmos_cuda_home="$(find "$_cosmos_site_packages/nvidia" -maxdepth 1 -type d -name 'cu[0-9]*' 2>/dev/null | head -n1)"
if [[ -n "$_cosmos_cuda_home" ]]; then
  export CUDA_HOME="$_cosmos_cuda_home"
fi
_cosmos_ld_dirs="$(find "$_cosmos_site_packages/nvidia" -maxdepth 2 -type d -name lib 2>/dev/null | paste -sd: -)"
# Many pip-installed NVIDIA libraries (libcublas, libcudnn*, libnccl, libcufft,
# etc.) ship only a versioned file (e.g. libcudart.so.13), not the unversioned
# libcudart.so symlink a full CUDA toolkit install would provide. A raw
# ctypes.CDLL("libcudart.so")/dlopen() call needs that exact filename to
# exist somewhere in LD_LIBRARY_PATH - it does no soname-based version
# resolution the way a compiled/linked binary's DT_NEEDED entry would. Create
# those missing unversioned symlinks in their own dir and put it first on
# LD_LIBRARY_PATH. Rebuilt (idempotently) every time this file is sourced, so
# it self-heals if the venv's nvidia packages ever change.
_cosmos_so_shim_dir="$_cosmos_env_dir/.cuda_so_shims"
mkdir -p "$_cosmos_so_shim_dir"
while IFS= read -r -d '' _cosmos_so; do
  _cosmos_so_base="$(basename "$_cosmos_so")"
  _cosmos_so_link="$_cosmos_so_shim_dir/${_cosmos_so_base%%.so.*}.so"
  [[ -e "$_cosmos_so_link" ]] || ln -s "$_cosmos_so" "$_cosmos_so_link"
done < <(find "$_cosmos_site_packages/nvidia" -iname "*.so.*" -print0 2>/dev/null)
_cosmos_ld_dirs="$_cosmos_so_shim_dir:$_cosmos_ld_dirs"
export LD_LIBRARY_PATH="$_cosmos_ld_dirs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
unset _cosmos_env_dir _cosmos_site_packages _cosmos_cuda_home _cosmos_ld_dirs _cosmos_so_shim_dir _cosmos_so _cosmos_so_base _cosmos_so_link
# Points training scripts (cosmos_policy.scripts.train, train_from_scratch_bc_demo.py)
# at the dataset root (see LIBERO.md's BASE_DATASETS_DIR convention). Override
# with COSMOS_POLICY_DATASETS_DIR if it differs from the storage root.
export BASE_DATASETS_DIR="${COSMOS_POLICY_DATASETS_DIR:-$COSMOS_POLICY_STORAGE}"
ENVEOF
chmod +x "$ENV_FILE"

# Source it now too: the download step below imports cosmos_utils, which
# transitively imports transformer_engine/megatron-core, hitting the exact
# same CUDA_HOME/LD_LIBRARY_PATH problem described above. Sourcing also pins
# HF_HOME (see activate_cuda_env.sh) for the duration of this script.
# shellcheck source=/dev/null
source "$ENV_FILE"
# ENV_FILE also sets HF_HUB_OFFLINE=1 (for later runtime use, once everything
# is cached - see activate_cuda_env.sh). This setup script's whole point is to
# populate that cache in the first place, so it needs live network access;
# undo it for the remainder of this script only.
unset HF_HUB_OFFLINE
HF_HOME_DIR="$HF_HOME"
mkdir -p "$HF_HOME_DIR"

# `hf auth login` writes its token to <HF_HOME>/token. Since HF_HOME is
# pinned above to this repo-local cache dir, a login done in a plain shell
# (the natural thing to do) lands its token in the *default* HF_HOME
# (~/.cache/huggingface) instead, which this pinned setup never sees -
# causing "gated repo" errors even for accounts that do have access. Copy it
# over if present.
DEFAULT_HF_TOKEN="$HOME/.cache/huggingface/token"
if [[ ! -f "$HF_HOME_DIR/token" && -f "$DEFAULT_HF_TOKEN" ]]; then
  echo "Copying Hugging Face auth token from $DEFAULT_HF_TOKEN into $HF_HOME_DIR..."
  cp "$DEFAULT_HF_TOKEN" "$HF_HOME_DIR/token"
fi

# Pre-download the pretrained LIBERO checkpoint assets now, at setup time,
# into that fixed repo-local Hugging Face cache (REPO_DIR/.hf_cache). This
# uses cosmos_policy's own download_hf_checkpoint()/download_hf_file()
# helpers (cosmos_policy/experiments/robot/cosmos_utils.py) - the exact same
# functions run_libero_eval.py calls at runtime for --ckpt_path,
# --dataset_stats_path and --t5_text_embeddings_path - so the cache is
# guaranteed to land wherever those calls will later look for it. Combined
# with HF_HOME pinned in activate_cuda_env.sh and HF_HUB_OFFLINE=1 in
# run_cosmos_policy_demo.sh, no download should ever be attempted at run
# time - which matters on clusters where compute nodes have no internet.
CKPT_REPO="nvidia/Cosmos-Policy-LIBERO-Predict2-2B"
echo "Downloading pretrained LIBERO checkpoint assets from Hugging Face ($CKPT_REPO, ~4 GB)..."
echo "If this repo is gated for your account, run '\"$VENV_DIR/bin/hf\" auth login' first and re-run this script."
"$VENV_DIR/bin/python" - <<PY
from cosmos_policy.experiments.robot.cosmos_utils import download_hf_checkpoint, download_hf_file

repo_id = "$CKPT_REPO"
ckpt_path = download_hf_checkpoint(repo_id)
print(f"Cached checkpoint at: {ckpt_path}")
for filename in ["libero_dataset_statistics.json", "libero_t5_embeddings.pkl"]:
    path = download_hf_file(f"{repo_id}/{filename}")
    print(f"Cached: {path}")
PY

# Two other kinds of "hf://" references also need pre-fetching, beyond the
# LIBERO checkpoint itself:
#  - cosmos_policy_experiment_configs.py calls get_checkpoint_path("hf://...")
#    directly at module level (not lazily), for base-model checkpoints used
#    as resume/init points for OTHER experiments in that same file. Because
#    every experiment in the file is registered eagerly on import, these
#    downloads happen the moment anything imports the config registry (e.g.
#    run_libero_eval.py) - regardless of which experiment you actually pick.
#  - config/defaults/tokenizer.py wires the video tokenizer/VAE to
#    "hf://nvidia/Cosmos-Predict2-2B-Video2World/tokenizer/tokenizer.pth" -
#    this one is NOT eager (wrapped in a LazyCall), so it's only fetched when
#    the model is actually constructed during eval, not at import time.
# NOTE: nvidia/Cosmos-Predict2-2B-Video2World is a ~54 GB repo (multiple
# resolutions/framerates plus a diffusers-format export) - fetch only the
# specific files actually used, not the whole repo.
# Pre-fetch all of these here via the same get_checkpoint_path() function
# cosmos_policy itself uses, so nothing is fetched at run_cosmos_policy_demo.sh
# time.
echo "Downloading base-model/tokenizer checkpoints referenced by the config registry..."
"$VENV_DIR/bin/python" - <<PY
from huggingface_hub.errors import GatedRepoError

from cosmos_policy._src.imaginaire.utils.checkpoint_db import get_checkpoint_path

for uri in [
    "hf://nvidia/Cosmos-Predict2-2B-Video2World/model-480p-16fps.pt",
    "hf://nvidia/Cosmos-Predict2-2B-Video2World/tokenizer/tokenizer.pth",
    "hf://nvidia/Cosmos-Policy-ALOHA-Predict2-2B/Cosmos-Policy-ALOHA-Predict2-2B.pt",
]:
    repo_id = uri[len("hf://") :].split("/")
    repo_id = f"{repo_id[0]}/{repo_id[1]}"
    try:
        path = get_checkpoint_path(uri)
        print(f"Cached: {path}")
    except GatedRepoError as e:
        raise SystemExit(
            f"\\nError: '{repo_id}' is a gated Hugging Face repo and either this "
            "account does not have access yet, or your login token has not been "
            "copied into this project's pinned HF_HOME (\$HF_HOME/token).\\n"
            f"  1. Request access at https://huggingface.co/{repo_id} "
            "(click 'Agree and access repository').\\n"
            '  2. Authenticate: "$VENV_DIR/bin/hf" auth login (needs a read-scoped '
            "token from https://huggingface.co/settings/tokens).\\n"
            "Then re-run this script (it copies ~/.cache/huggingface/token into "
            "the pinned cache if needed).\\n"
        ) from e
PY

# The `libero` pip package (installed via the "libero" dependency group) also
# needs its own 3D simulation assets (object meshes/textures/scenes, ~286 MB
# from jadechoghari/libero-assets on HF). It fetches these itself, lazily, on
# first environment build via libero.libero.get_assets_path() - completely
# separate from cosmos_policy's own checkpoint downloads above, and into a
# hardcoded ~/.cache/libero/assets (NOT affected by the pinned HF_HOME).
# Trigger that download here too so run_cosmos_policy_demo.sh never needs to.
echo "Downloading LIBERO simulator assets (jadechoghari/libero-assets, ~286 MB)..."
"$VENV_DIR/bin/python" -c "
from libero.libero.utils.download_utils import download_assets_from_huggingface
print('Assets at:', download_assets_from_huggingface())
"

# Pre-download the LIBERO-Cosmos-Policy *training* dataset (demonstrations +
# rollouts across LIBERO-Spatial/Object/Goal/LIBERO-10) - separate from the
# pretrained checkpoint downloaded above, and only needed for launching
# training (cosmos_policy.scripts.train / train_from_scratch_bc_demo.py), not
# for eval. `hf download` resumes partial downloads, so re-running this
# script is safe even if a previous attempt was interrupted.
#
# This dataset (many GB, thousands of files under all_episodes/) goes to
# DATASETS_DIR instead of under $REPO_DIR: unlike the checkpoint/tokenizer/
# asset downloads above, it's easily large enough to blow a small $HOME quota
# on clusters (e.g. Compute Canada RRG allocations), so it defaults to the
# project storage root (COSMOS_POLICY_STORAGE). Override with
# COSMOS_POLICY_DATASETS_DIR if that path isn't right for you.
DATASETS_DIR="${COSMOS_POLICY_DATASETS_DIR:-${COSMOS_POLICY_STORAGE:-/project/aip-courvill/esraa1}}"
mkdir -p "$DATASETS_DIR"
DATASET_REPO="nvidia/LIBERO-Cosmos-Policy"
DATASET_DIR="$DATASETS_DIR/LIBERO-Cosmos-Policy"
echo "Downloading LIBERO-Cosmos-Policy training dataset from Hugging Face ($DATASET_REPO)..."
echo "  -> $DATASET_DIR"
echo "If this repo is gated for your account, run '\"$VENV_DIR/bin/hf\" auth login' first and re-run this script."
# This dataset's thousands of small files reliably trip HF's per-5-minute API
# rate limit (one xet-read-token request per file) even at the default 8
# workers, well before the transfer finishes. Retry with backoff - each
# retry resumes rather than restarting, so this just rides out the 429s.
for _cosmos_dl_attempt in 1 2 3 4 5; do
  if "$VENV_DIR/bin/hf" download "$DATASET_REPO" --repo-type dataset --local-dir "$DATASET_DIR" --max-workers 4; then
    break
  fi
  if [[ "$_cosmos_dl_attempt" -eq 5 ]]; then
    echo "Error: dataset download kept hitting HF's rate limit after 5 attempts. Wait a few minutes and re-run this script (it resumes)." >&2
    exit 1
  fi
  echo "Dataset download hit an error (likely HF rate limiting) - waiting 60s before retry $_cosmos_dl_attempt/5..."
  sleep 60
done
unset _cosmos_dl_attempt

# activate_cuda_env.sh already exports BASE_DATASETS_DIR (derived from
# COSMOS_POLICY_STORAGE in the heredoc above) - no separate append needed now
# that the dataset root is a single knob rather than resolved only at this point.

cat <<EOF

Setup complete.

Repository:
  $REPO_DIR

Virtual environment:
  $VENV_DIR

CUDA env file (this host has no system-wide CUDA toolkit, so source this
before running any cosmos_policy Python command - see comments in the file):
  source "$ENV_FILE"

Pretrained checkpoint ($CKPT_REPO) is already downloaded and
cached in $HF_HOME_DIR. Sourcing $ENV_FILE (as
run_cosmos_policy_demo.sh does) pins HF_HOME to that same directory and
sets HF_HUB_OFFLINE=1, so nothing gets re-downloaded at run time.

Training dataset ($DATASET_REPO) is already downloaded to:
  $DATASET_DIR
Sourcing $ENV_FILE also exports COSMOS_POLICY_STORAGE / COSMOS_POLICY_ACCOUNT /
COSMOS_POLICY_GPU_TYPE (the per-cluster knobs) and BASE_DATASETS_DIR="$DATASETS_DIR" so training
scripts (cosmos_policy.scripts.train, train_from_scratch_bc_demo.py) and the
conf/runs/*.yaml sweep configs find their paths automatically.

Run the interactive quickstart without activating the environment:
  cd "$REPO_DIR" && source "$ENV_FILE"
  "$VENV_DIR/bin/python"

Or activate the environment first:
  cd "$REPO_DIR" && source "$ENV_FILE"
  source "$VENV_DIR/bin/activate"
  python

Example LIBERO evaluation (see LIBERO.md in the repo for the full flag list
and how to adjust --available_gpus / --task_suite_name / --seed):
  cd "$REPO_DIR" && source "$ENV_FILE"
  "$VENV_DIR/bin/python" -m cosmos_policy.experiments.robot.libero.run_libero_eval \\
    --config cosmos_predict2_2b_480p_libero__inference_only \\
    --ckpt_path nvidia/Cosmos-Policy-LIBERO-Predict2-2B \\
    --config_file cosmos_policy/config/config.py \\
    --task_suite_name libero_10 \\
    --available_gpus "0" \\
    --seed 195

For a quick smoke test that runs one trial and records rollout videos, see:
  bash run_cosmos_policy_demo.sh "$REPO_DIR"

Example from-scratch behavior-cloning demo (trains on a single easy LIBERO
task - see cosmos_policy/scripts/train_from_scratch_bc_demo.py):
  cd "$REPO_DIR" && source "$ENV_FILE"
  "$VENV_DIR/bin/python" -m cosmos_policy.scripts.train_from_scratch_bc_demo \\
    --task-suite libero_object --task-keyword alphabet_soup \\
    --work-dir /tmp/from_scratch_bc_demo --max-iter 200
EOF
