#!/usr/bin/env bash
set -euo pipefail

# Native (non-Docker) setup for NVIDIA's Cosmos Policy using uv.
# https://github.com/nvlabs/cosmos-policy
#
# Usage:
#   bash setup_cosmos_policy_uv.sh [INSTALL_DIR]
#
# Example:
#   bash setup_cosmos_policy_uv.sh "$PWD/cosmos_policy"
#
# Requirements:
#   - git
#   - uv (https://docs.astral.sh/uv/getting-started/installation/)
#   - an NVIDIA GPU with CUDA 13.0 drivers (this script installs the "cu130" extra)
#   - system packages that the project's own docker/Dockerfile installs via apt,
#     since this script does not use Docker and will not sudo-install anything:
#       build-essential cmake ffmpeg git-lfs libgl1 libegl1-mesa-dev \
#       libgl1-mesa-dri libglib2.0-0
#     Plus libglu1-mesa (not in the Dockerfile, but needed by robosuite's EGL
#     context teardown - without it you'll see a harmless-but-noisy
#     "libGLU.so.0: cannot open shared object file" during interpreter
#     shutdown, after a LIBERO eval already finished successfully):
#     On Debian/Ubuntu:
#       sudo apt-get install -y build-essential cmake ffmpeg git-lfs libgl1 \
#         libegl1-mesa-dev libgl1-mesa-dri libglib2.0-0 libglu1-mesa
#
# This script installs the "libero" task group (LIBERO simulation benchmark).
# robocasa and aloha are mutually exclusive alternatives - see LIBERO.md /
# ROBOCASA.md / ALOHA.md in the cloned repo if you need a different one.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${1:-$SCRIPT_DIR/cosmos_policy}"
CUDA_EXTRA="cu130"
TASK_GROUP="libero"
PYTHON_VERSION="3.10"

# Resolve relative install paths from the caller's cwd (not from inside REPO_DIR).
if [[ "$INSTALL_DIR" != /* ]]; then
  INSTALL_DIR="$(pwd)/$INSTALL_DIR"
fi
REPO_DIR="$INSTALL_DIR"

command -v git >/dev/null 2>&1 || {
  echo "Error: git is required." >&2
  exit 1
}

command -v uv >/dev/null 2>&1 || {
  echo "Error: uv is required." >&2
  echo "Install it from https://docs.astral.sh/uv/getting-started/installation/" >&2
  exit 1
}

for tool in cmake ffmpeg gcc; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "Warning: '$tool' was not found on PATH." >&2
    echo "  Cosmos Policy's own Dockerfile installs it via apt; some pip/uv" >&2
    echo "  builds (e.g. mujoco, flash-attn) may fail to compile without it." >&2
  }
done

# cosmos_policy is meant to live as plain, committable source under this
# repo (not a nested git checkout - a nested .git makes the parent repo treat
# it as an opaque gitlink instead of tracking its files). If the source is
# already present (e.g. already committed here), leave it alone. Otherwise
# fetch it via a throwaway git clone and immediately strip its .git, so the
# result is just files, ready to be committed to the parent repo.
if [[ -f "$REPO_DIR/pyproject.toml" ]]; then
  echo "cosmos-policy source already present at $REPO_DIR"
else
  if [[ -e "$REPO_DIR" ]]; then
    echo "Removing incomplete install directory at $REPO_DIR"
    rm -rf "$REPO_DIR"
  fi
  git clone https://github.com/nvlabs/cosmos-policy.git "$REPO_DIR"
  rm -rf "$REPO_DIR/.git"
fi

REPO_DIR="$(cd "$REPO_DIR" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
UV_HOME_DIR="$REPO_DIR/.uv_home"
export UV_HOME="$UV_HOME_DIR"
export XDG_DATA_HOME="$UV_HOME_DIR/xdg_data"
export XDG_CACHE_HOME="$UV_HOME_DIR/xdg_cache"
export UV_PYTHON_INSTALL_DIR="$REPO_DIR/.uv_python"

# Ensure uv cache/temp are writable even in restricted/sandboxed environments.
mkdir -p "$REPO_DIR/.uv_cache" "$REPO_DIR/.uv_tmp"
export UV_CACHE_DIR="$REPO_DIR/.uv_cache"
export TMPDIR="$REPO_DIR/.uv_tmp"

cd "$REPO_DIR"

# pyproject.toml requires Python >= 3.10; uv downloads a compatible
# interpreter automatically when necessary.
mkdir -p "$UV_PYTHON_INSTALL_DIR"
uv python install "$PYTHON_VERSION" --install-dir "$UV_PYTHON_INSTALL_DIR" --no-bin

# Resolve and install the pinned dependencies (core + cu130 CUDA extra +
# libero task group) into a uv-managed venv at $REPO_DIR/.venv.
uv sync --extra "$CUDA_EXTRA" --group "$TASK_GROUP" --python "$PYTHON_VERSION"

# On hosts with no system-wide CUDA toolkit (no nvcc, nothing in ldconfig),
# transformer_engine/megatron-core still try to locate CUDA .so files via
# CUDA_HOME and ldconfig, using a search layout that predates the current
# consolidated "nvidia-cuXX" pip wheels (which put every CUDA library under a
# single nvidia/cuXX/lib/ dir instead of one dir per library). Without this,
# `import transformer_engine` fails with e.g.
# "subprocess.CalledProcessError: ldconfig -p | grep 'libnvrtc.so'" or later
# "OSError: libcublas.so.13: cannot open shared object file". Generate an env
# file that points CUDA_HOME/LD_LIBRARY_PATH at the venv's own CUDA libs so
# any script that sources it can import these packages successfully.
ENV_FILE="$REPO_DIR/activate_cuda_env.sh"
cat >"$ENV_FILE" <<'ENVEOF'
#!/usr/bin/env bash
# Generated by setup_cosmos_policy_uv.sh - source this before running any
# cosmos_policy Python command:
#   source "$(dirname "${BASH_SOURCE[0]}")/activate_cuda_env.sh"
_cosmos_env_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Pin HF_HOME to a fixed, repo-local cache dir (overriding any HF_HOME/module
# default from the surrounding shell) so downloads always land where the
# setup script's pre-fetch step put them - see setup_cosmos_policy_uv.sh.
export HF_HOME="$_cosmos_env_dir/.hf_cache"
_cosmos_site_packages="$(find "$_cosmos_env_dir/.venv/lib" -maxdepth 1 -type d -name 'python3.*' | head -n1)/site-packages"
_cosmos_cuda_home="$(find "$_cosmos_site_packages/nvidia" -maxdepth 1 -type d -name 'cu[0-9]*' 2>/dev/null | head -n1)"
if [[ -n "$_cosmos_cuda_home" ]]; then
  export CUDA_HOME="$_cosmos_cuda_home"
fi
_cosmos_ld_dirs="$(find "$_cosmos_site_packages/nvidia" -maxdepth 2 -type d -name lib 2>/dev/null | paste -sd: -)"
if [[ -n "$_cosmos_ld_dirs" ]]; then
  export LD_LIBRARY_PATH="$_cosmos_ld_dirs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
unset _cosmos_env_dir _cosmos_site_packages _cosmos_cuda_home _cosmos_ld_dirs
ENVEOF
chmod +x "$ENV_FILE"

# Source it now too: the download step below imports cosmos_utils, which
# transitively imports transformer_engine/megatron-core, hitting the exact
# same CUDA_HOME/LD_LIBRARY_PATH problem described above. Sourcing also pins
# HF_HOME (see activate_cuda_env.sh) for the duration of this script.
# shellcheck source=/dev/null
source "$ENV_FILE"
HF_HOME_DIR="$HF_HOME"
mkdir -p "$HF_HOME_DIR"

# `hf auth login` writes its token to <HF_HOME>/token. Since HF_HOME is
# pinned above to this repo-local cache dir, a login done in a plain shell
# (the natural thing to do) lands its token in the *default* HF_HOME
# (~/.cache/huggingface) instead, which this pinned setup never sees -
# causing "gated repo" errors even for accounts that do have access. Copy it
# over if present.
DEFAULT_HF_TOKEN="$HOME/.cache/huggingface/token"
if [[ ! -f "$HF_HOME_DIR/token" && -f "$DEFAULT_HF_TOKEN" ]]; then
  echo "Copying Hugging Face auth token from $DEFAULT_HF_TOKEN into $HF_HOME_DIR..."
  cp "$DEFAULT_HF_TOKEN" "$HF_HOME_DIR/token"
fi

# Pre-download the pretrained LIBERO checkpoint assets now, at setup time,
# into that fixed repo-local Hugging Face cache (REPO_DIR/.hf_cache). This
# uses cosmos_policy's own download_hf_checkpoint()/download_hf_file()
# helpers (cosmos_policy/experiments/robot/cosmos_utils.py) - the exact same
# functions run_libero_eval.py calls at runtime for --ckpt_path,
# --dataset_stats_path and --t5_text_embeddings_path - so the cache is
# guaranteed to land wherever those calls will later look for it. Combined
# with HF_HOME pinned in activate_cuda_env.sh and HF_HUB_OFFLINE=1 in
# run_cosmos_policy_demo.sh, no download should ever be attempted at run
# time - which matters on clusters where compute nodes have no internet.
CKPT_REPO="nvidia/Cosmos-Policy-LIBERO-Predict2-2B"
echo "Downloading pretrained LIBERO checkpoint assets from Hugging Face ($CKPT_REPO, ~4 GB)..."
echo "If this repo is gated for your account, run '\"$VENV_DIR/bin/hf\" auth login' first and re-run this script."
"$VENV_DIR/bin/python" - <<PY
from cosmos_policy.experiments.robot.cosmos_utils import download_hf_checkpoint, download_hf_file

repo_id = "$CKPT_REPO"
ckpt_path = download_hf_checkpoint(repo_id)
print(f"Cached checkpoint at: {ckpt_path}")
for filename in ["libero_dataset_statistics.json", "libero_t5_embeddings.pkl"]:
    path = download_hf_file(f"{repo_id}/{filename}")
    print(f"Cached: {path}")
PY

# Two other kinds of "hf://" references also need pre-fetching, beyond the
# LIBERO checkpoint itself:
#  - cosmos_policy_experiment_configs.py calls get_checkpoint_path("hf://...")
#    directly at module level (not lazily), for base-model checkpoints used
#    as resume/init points for OTHER experiments in that same file. Because
#    every experiment in the file is registered eagerly on import, these
#    downloads happen the moment anything imports the config registry (e.g.
#    run_libero_eval.py) - regardless of which experiment you actually pick.
#  - config/defaults/tokenizer.py wires the video tokenizer/VAE to
#    "hf://nvidia/Cosmos-Predict2-2B-Video2World/tokenizer/tokenizer.pth" -
#    this one is NOT eager (wrapped in a LazyCall), so it's only fetched when
#    the model is actually constructed during eval, not at import time.
# NOTE: nvidia/Cosmos-Predict2-2B-Video2World is a ~54 GB repo (multiple
# resolutions/framerates plus a diffusers-format export) - fetch only the
# specific files actually used, not the whole repo.
# Pre-fetch all of these here via the same get_checkpoint_path() function
# cosmos_policy itself uses, so nothing is fetched at run_cosmos_policy_demo.sh
# time.
echo "Downloading base-model/tokenizer checkpoints referenced by the config registry..."
"$VENV_DIR/bin/python" - <<PY
from huggingface_hub.errors import GatedRepoError

from cosmos_policy._src.imaginaire.utils.checkpoint_db import get_checkpoint_path

for uri in [
    "hf://nvidia/Cosmos-Predict2-2B-Video2World/model-480p-16fps.pt",
    "hf://nvidia/Cosmos-Predict2-2B-Video2World/tokenizer/tokenizer.pth",
    "hf://nvidia/Cosmos-Policy-ALOHA-Predict2-2B/Cosmos-Policy-ALOHA-Predict2-2B.pt",
]:
    repo_id = uri[len("hf://") :].split("/")
    repo_id = f"{repo_id[0]}/{repo_id[1]}"
    try:
        path = get_checkpoint_path(uri)
        print(f"Cached: {path}")
    except GatedRepoError as e:
        raise SystemExit(
            f"\\nError: '{repo_id}' is a gated Hugging Face repo and either this "
            "account does not have access yet, or your login token has not been "
            "copied into this project's pinned HF_HOME (\$HF_HOME/token).\\n"
            f"  1. Request access at https://huggingface.co/{repo_id} "
            "(click 'Agree and access repository').\\n"
            '  2. Authenticate: "$VENV_DIR/bin/hf" auth login (needs a read-scoped '
            "token from https://huggingface.co/settings/tokens).\\n"
            "Then re-run this script (it copies ~/.cache/huggingface/token into "
            "the pinned cache if needed).\\n"
        ) from e
PY

# The `libero` pip package (installed via the "libero" dependency group) also
# needs its own 3D simulation assets (object meshes/textures/scenes, ~286 MB
# from jadechoghari/libero-assets on HF). It fetches these itself, lazily, on
# first environment build via libero.libero.get_assets_path() - completely
# separate from cosmos_policy's own checkpoint downloads above, and into a
# hardcoded ~/.cache/libero/assets (NOT affected by the pinned HF_HOME).
# Trigger that download here too so run_cosmos_policy_demo.sh never needs to.
echo "Downloading LIBERO simulator assets (jadechoghari/libero-assets, ~286 MB)..."
"$VENV_DIR/bin/python" -c "
from libero.libero.utils.download_utils import download_assets_from_huggingface
print('Assets at:', download_assets_from_huggingface())
"

cat <<EOF

Setup complete.

Repository:
  $REPO_DIR

Virtual environment:
  $VENV_DIR

CUDA env file (this host has no system-wide CUDA toolkit, so source this
before running any cosmos_policy Python command - see comments in the file):
  source "$ENV_FILE"

Pretrained checkpoint ($CKPT_REPO) is already downloaded and
cached in $HF_HOME_DIR. Sourcing $ENV_FILE (as
run_cosmos_policy_demo.sh does) pins HF_HOME to that same directory and
sets HF_HUB_OFFLINE=1, so nothing gets re-downloaded at run time.

Run the interactive quickstart without activating the environment:
  cd "$REPO_DIR" && source "$ENV_FILE"
  "$VENV_DIR/bin/python"

Or activate the environment first:
  cd "$REPO_DIR" && source "$ENV_FILE"
  source "$VENV_DIR/bin/activate"
  python

Example LIBERO evaluation (see LIBERO.md in the repo for the full flag list
and how to adjust --available_gpus / --task_suite_name / --seed):
  cd "$REPO_DIR" && source "$ENV_FILE"
  "$VENV_DIR/bin/python" -m cosmos_policy.experiments.robot.libero.run_libero_eval \\
    --config cosmos_predict2_2b_480p_libero__inference_only \\
    --ckpt_path nvidia/Cosmos-Policy-LIBERO-Predict2-2B \\
    --config_file cosmos_policy/config/config.py \\
    --task_suite_name libero_10 \\
    --available_gpus "0" \\
    --seed 195

For a quick smoke test that runs one trial and records rollout videos, see:
  bash run_cosmos_policy_demo.sh "$REPO_DIR"
EOF
